//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.9-04/09/2009 09:05 AM(mockbuild)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.10 at 10:50:20 PM EEST 
//


package com.epam.by.entity;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.epam.by.entity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.epam.by.entity
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Customers.Customer.Phone }
     * 
     */
    public Customers.Customer.Phone createCustomersCustomerPhone() {
        return new Customers.Customer.Phone();
    }

    /**
     * Create an instance of {@link Customers }
     * 
     */
    public Customers createCustomers() {
        return new Customers();
    }

    /**
     * Create an instance of {@link Customers.Customer.Email }
     * 
     */
    public Customers.Customer.Email createCustomersCustomerEmail() {
        return new Customers.Customer.Email();
    }

    /**
     * Create an instance of {@link Customers.Customer }
     * 
     */
    public Customers.Customer createCustomersCustomer() {
        return new Customers.Customer();
    }

}
